export const AZURE_STORAGE_QUEUE_HANDLERS = 'AZURE_STORAGE_QUEUE_HANDLERS';
export const AZURE_STORAGE_QUEUE_CONFIG_PROVIDER =
  'AZURE_STORAGE_QUEUE_CONFIG_PROVIDER';

export const AZURE_STORAGE_QUEUE_HANDLER_METADATA =
  'AZURE_STORAGE_QUEUE_HANDLER_METADATA';
